- app/src/main/res/values-lt/strings.xml
> Lithuanian strings xml file

- app/src/main/res/values-lt/strings.xml
Updated lithuanian strings.xml
> Updated lithuanian translation

- app/src/main/res/values-it/strings.xml
> Translate app to Italian

- app/src/main/res/values-de/strings.xml
I've completed the German translation.
> Issue #26 German translation

- app/src/main/res/values-nl/strings.xml
Hi, did the translation for Dutch (could/can be used for Belgium (Flemish part) and The Netherlands). Let me know if I missed anything.
> #26 nl translation

- app/src/main/res/values-ar/strings.xml
> Arabic translation

- app/src/main/res/values-fr/strings.xml
> Translations #26 - French

- app/src/main/res/values-ru/strings.xml
Add Russian translation for the app
> Add russian translation

- app/src/main/res/values-es/strings.xml
In the app, I noticed that I've missed a translation so I just fixed it and committed the change. However, you'll notice 3 commits and that's because in the first commit my usual github username didn't appear. I used the second commit to revert the first commit but I still don't know if it was a good idea. The last commit is just fine. I hope this doesn't cause any trouble.
> #26 es translation. Missing translation. 

- app/src/main/res/values-dk/strings.xml
New strings translated and fixed a few of the old ones.
> #26 Danish translation

- app/src/main/res/values-sv/strings.xml
I have translated the app into swedish.
> Added #26 swedish (sv) language support.

- app/src/main/res/values-ru/strings.xml
Added translation for play_folder, pref_title_play_from_here and pref_description_play_from_here Strings.
> #26 <russian> translation

- app/src/main/res/values-es/strings.xml
Here's my modest contribution to improving the Spanish translation.
Thanks for the opportunity of submitting my first pull request!
> #26 Improve Spanish translation

- README.md
- app/src/main/res/values-es/strings.xml
This addresses @ScreamingHawk's latest comments on issue #26, in reference to a new string to be translated. I've taken the opportunity to improve other existing Spanish translations.
As a bonus, I've fixed a small typo in the README.md file.
> Additional Spanish translations

- app/src/main/res/values-fr/strings.xml
Thank you Michael,
Here come some updates and  missing keks in string.xml.
Thomas
> #24 Translators deserve more credit - French

- app/src/main/res/values-nl/strings.xml
Added the credits for the Dutch translation
> #26 Update Dutch translation

- app/src/main/res/values-zh/strings.xml
just have a few more sentences of technical translation to go through
> #26 zh translation

- app/src/main/res/values-pt/strings.xml
Requesting the Pull with Portuguese Translaction.
Thank you @ScreamingHawk
> #26 portuguese translaction

- app/src/main/res/values-nl/strings.xml
> #26 Dutch translation update

- app/src/main/res/values-zh/strings.xml
Hi there,I have found your project very interesting, however the translation in chinese have many faults so I modified some of the translation,and added some setences that haven't translated.
I hope you like this version of translation and accept my PR :)
Thank you!
> Modified various Chinese translations

- app/src/main/res/values-vi/strings.xml
Translated the strings.xml into vietnamese.
> # 26 Vietnamese translation

- app/src/main/AndroidManifest.xml
- app/src/main/java/link/standen/michael/slideshow/CreditsActivity.java
- app/src/main/res/layout/activity_credits.xml
- app/src/main/res/values-ru/strings.xml
I think this activity has to have a back button in appBar. I missed it when I tried to use the app
> Add back button to Credits activity

- app/src/main/res/values-de/strings.xml
I corrected some errors in the German translation and also added some missing strings.
Remark: I could not execute the application with the new file and verify it,  because I am having some problems setting up the SDK...
> #26 improved German translation and added missing strings

- app/build.gradle
- app/src/main/java/link/standen/michael/slideshow/strategy/image/CustomImageStrategy.java
- app/src/main/java/link/standen/michael/slideshow/strategy/image/custom/CustomRotateDimenTransformation.java
- app/src/main/res/values-de/strings.xml
Removed the warnig, code should be ready now.
> #101 Add support for EXIF orientation

- app/src/main/res/values-ru/strings.xml
I've added missing Russian translations and reformated code to match the English version
> Add missing translations, reformat code to match the English version

- app/src/main/res/values-pl/strings.xml
This translation is my little comittment to this nice project.
> #26 Polish translation
